"""add quotation lines

Revision ID: 727f64391be6
Revises: d7b91d90f77a
Create Date: 2026-01-31 13:59:02.657987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '727f64391be6'
down_revision: Union[str, None] = 'd7b91d90f77a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quotation_lines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('quotation_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('vendor_id', sa.UUID(), nullable=False),
    sa.Column('variant_id', sa.UUID(), nullable=True),
    sa.Column('rental_start', sa.DateTime(), nullable=False),
    sa.Column('rental_end', sa.DateTime(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price_per_unit', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vendor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quotation_lines_quotation_id'), 'quotation_lines', ['quotation_id'], unique=False)
    op.add_column('quotations', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.alter_column('quotations', 'customer_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('quotations', 'status',
               existing_type=postgresql.ENUM('DRAFT', 'SENT', 'CONFIRMED', name='quotationstatus'),
               nullable=False)
    op.create_index(op.f('ix_quotations_customer_id'), 'quotations', ['customer_id'], unique=False)
    op.drop_column('quotations', 'total_amount')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quotations', sa.Column('total_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_quotations_customer_id'), table_name='quotations')
    op.alter_column('quotations', 'status',
               existing_type=postgresql.ENUM('DRAFT', 'SENT', 'CONFIRMED', name='quotationstatus'),
               nullable=True)
    op.alter_column('quotations', 'customer_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('quotations', 'created_at')
    op.drop_index(op.f('ix_quotation_lines_quotation_id'), table_name='quotation_lines')
    op.drop_table('quotation_lines')
    # ### end Alembic commands ###
